### ISSUE TITLE
IMAGE LINKEDIN

### ISSUE THREAD

**Issue by nlnadialigia** [riccomoura/riccomoura#1]
Alterar o src do link do Linkedin que está quebrado.

![Captura de tela de 2021-06-01 15-36-26](https://user-images.githubusercontent.com/66634283/120373869-3eb5b480-c2ef-11eb-8545-f9c2be86ae9c.png)

 <a href="https://www.linkedin.com/in/mesquitahenrique">
    <img src="https://img.shields.io/badge/-Linkedin-0e75b6?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/mesquitahenrique">
  </a>

**Comment by riccomoura** [comment]
Valeu, @nlnadialigia ! To tentando encontrar uma badge do LinkedIn para substituição, tem alguma sugestão?
